### ISSUE TITLE
Please see me in my office hours

### ISSUE THREAD

**Issue by jewpaltz** [eyeboah369/WebProgramming-Exercise-App-#1]
B"H

Overall your project looks good.
I'd like to know which tutorials you are following.
You code is obviously not based on what we are doing in class.
As long as you understand what you are doing that is fine. But I want to go over some of it with you.

**Comment by eyeboah369** [comment]
I am not following one specific tutorial or set of tutorials for this project. I have some experiences working in web development from before this course and using JS based languages/libraries so most of this is just looking up guidance when I become stuck on proper setup for connecting a front end to a backend. I am still confused about the issue of my work not being based on what we are doing in class. Everything you have gone over I have actively tried to incorporate into my project (From Node.js setup, express, Vue, Vue state, git, nodemon, vuetify, Bulma, etc), if the issue is that I have gone beyond what you have gotten up to it is only because I am very interested in finishing this project and continuing to learn how to integrate new features I did not know of before. I do understand what I have coded, from my commit history this is something that I have been working on actively since the early days of the semester and have learned a lot about web development. I will try to visit your office hours for this coming week, thank you for opening the issue with feedback.

**Comment by jewpaltz** [comment]
There is no issue. I even wrote "As long as you understand what you are doing that is fine. "
Your code just looks extremely similar to code that a few students turned in last year, but that they couldn't get to work because they had no clue what they were actually doing.

There are also 2 students that I saw so far that have code that also seems to be based on your code (or from the same place) however they were not able to get it right, and if I know where they got it from it will help me help them.
